FROM golang:1.23.1-bullseye

ENV OS=linux
ENV GO111MODULE=on
ENV PKGPATH=github.com/inigohu/valkey

# copy current workspace
WORKDIR ${GOPATH}/src/${PKGPATH}
COPY . ${GOPATH}/src/${PKGPATH}

RUN go mod download
