apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: valkey
  labels:
    app: valkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
        - name: valkey
          image: inigohu/valkey:latest
          imagePullPolicy: Always
          command:
            - valkey
          args:
            - client
            - --config
            - /config/valkey.yaml
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: valkey
      serviceAccountName: valkey
